{% set name = "segment-anything" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/segment-anything-py/segment_anything_py-{{ version }}.tar.gz
  sha256: 91d7d65804dd3a9030e26cd269991c4d24099008fb82e5ae98c9f6d9163b4b75

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pytorch >=1.7
    - torchvision >=0.8
    - opencv
    - pycocotools
    - matplotlib-base
    - onnxruntime
    - onnx

test:
  imports:
    - segment_anything
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/opengeos/segment-anything
  summary: An unofficial Python package for Meta AI's Segment Anything Model
  description: An unofficial Python package for Meta AI's Segment Anything Model
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
